import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import { QueryProvider } from "@/providers/query-provider";

import toast, { Toaster } from 'react-hot-toast';
import { NewAccountSheet } from "@/features/accounts/components/new-account-sheet";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: `${process.env.NEXT_PUBLIC_APP_NAME}`,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <QueryProvider>
            <NewAccountSheet />
            <Toaster
              position="bottom-left"
              reverseOrder={false}
            />
            {children}
          </QueryProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
